title: Ticia Dunn's Resume
author: Ticia Dunn
email: dunnticia633@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a recent college graduate looking to pursue a career in Computer Science, particularly the Web Development field. 
  My original degree was in Chemistry but as I've worked in the laboratory field, 
  I've realized it's not for me and am ready for a change. 
  Hopefully the Awesome Inc Bootcamp is just what I need to find the career I'm looking for in a field I actually enjoy.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
